Reg al
inbo/forrescalc pull request #100
Opened 2022-03-25 14:25 UTC by leymanan

2022-03-25 14:50 UTC, leymanan commented
@ElsLommelen : ik heb dus beide branches teruggezet naar de situatie van voor mijn flater.
Dan PR van branch `reg_AL `naar branch `statistics`, om de verschilpunten te bekijken.
Die heb ik allemaal opgelost en nu dus gecommit.
Deze morgen had ik dan ook al direct gemerged, maar dat doe ik nu dus niet !

Wat zijn nu volgende stappen?
Jij bekijkt deze commit? 
En als dat allemaal OK is, dan mag de PR die jij aangemaakt hebt van branch `statistics `naar `reg_AL `gemerged worden?
En dan ben ik het die die mergemoet doen, omdat het in mijn branch reg_AL dat alles toegeveogd wordt?
Klopt dat?
Dus dan ligt de bal nu even bij u?
(en nog ne keer sorry voor al deze rompslomp: ik ben dit jaar gestart met leuze "progress instead of perfection", maar soms heeft dat toch negatieve effecten :-( )
(over 't algemeen ben ik iemand die alles teveel overdenkt en daardoor wat traag vooruitgaat ...)

2022-03-25 15:26 UTC, ElsLommelen commented
Heb je behalve het oplossen van de conflicten ook gekeken naar de verschilpunten die er nu nog overblijven tussen de twee branches?  (Rechtsboven onder de tab 'Files changed', waar je de reviews doet.)  Als je hier nog achter staat, ligt de bal inderdaad terug bij mij.

> En als dat allemaal OK is, dan mag de PR die jij aangemaakt hebt van branch `statistics `naar `reg_AL `gemerged worden?
> En dan ben ik het die die merge moet doen, omdat het in mijn branch `reg_AL` is dat alles toegevoegd wordt?
> Klopt dat?

Euh, nee, omgekeerd.  Jij hebt nu de branch `reg_AL` in orde gebracht, dus ik review die om in `statistics` toe te voegen.  Daarna kijk ik nog even aan welke commentaren in de PR van `statistics` nog niet voldaan is, en werk `statistics` verder af.  En als dat in orde is om in de main te mergen, dan mag je het eerst nog eens nakijken als je wil.

Geen probleem van de rompslomp.  Het heeft trouwens ook goede effecten: hopelijk heb je er een en ander van bijgeleerd (wat je beter niet doet, en ook hoe je de boel terug herstelt).  Af en toe moet je eens tegen een muur durven lopen om bij te leren...

En ja, laat die merge voor deze keer maar zo, hoor.  Als we het geen halfjaar laten liggen, weten we nog wel dat die voorlopig niet weg mag.

Trouwens, wat uw PR betreft: je had ook de oude terug kunnen opvissen en opnieuw openen, vermoed ik...  ;-)

2022-03-25 16:58 UTC, leymanan commented
> Heb je behalve het oplossen van de conflicten ook gekeken naar de verschilpunten die er nu nog overblijven tussen de twee branches? (Rechtsboven onder de tab 'Files changed', waar je de reviews doet.) Als je hier nog achter staat, ligt de bal inderdaad terug bij mij.

ik heb nog kleine aanpassingen gedaan aan 4 scripts. 
Volgens mij zijn er nu geen verschilpunten meer waar ik niet achter sta ;-)

2022-03-29 13:30 UTC, ElsLommelen requested changes
Ik heb je aanpassingen nagekeken en enkele opmerkingen genoteerd.  Ik heb daarna de verschillende functies gerund, en ik kreeg (als verwacht, zie opmerking hieronder) een error bij `calculate_vegetation()`.  `calculate_dendrometry()` en `calculate_regeneration()` en alle functies die hiervoor eerst gerund moeten worden, waren wel in orde.

Ah ja, ik merkte ook dat in het script `Main.R` de berekening van de hoogtemodellen nog niet opgenomen was, ik zal even een PR maken om dit toe te voegen, zodat we het niet vergeten.  (Dat hangt strikt genomen niet van deze branch af en ook niet van statistics, dat hebben we blijkbaar eerder al over het hoofd gezien.)  Voeg je deze ook nog even toe?

2022-04-07 06:34 UTC, leymanan commented on R/calculate_vegetation_plot.R
> +        100 * (1 - (1 - .data$shrub_cover_mean / 100) * (1 - .data$tree_cover_mean / 100)),
> * de term 'mean' enkel gebruiken voor effectieve gemiddeldes, en niet voor een midden van een interval.  (Dit consequent toepassen, gaat helpen om gemakkelijker het onderscheid te kunnen maken tussen individuele metingen en geaggregeerde resultaten.)

Inderdaad logisch!
Denk dat een deel van de onlogica voortkomt uit feit dat deze toevoegingen gebeurd zijn voor branch `statistics `toegevoegd werd ...
Ik heb nu enkel mid bewaard, en extra info bij documentatie

2022-04-07 06:35 UTC, leymanan commented on R/read_forresdat.R
> +#' add columns plottype, forest_reserve, survey_dendro/deadw/reg/veg (T or F) and data_processed (T or F)?  Default is TRUE.  (This is only
OK!

2022-04-07 06:37 UTC, leymanan commented on R/read_forresdat.R
> +#' add columns plottype, forest_reserve, survey_dendro/deadw/reg/veg (T or F) and data_processed (T or F)?  Default is TRUE.  (This is only
OK, dat had je inderdaad ook in branch `statistics `al aangegeven, maar deze aanpassingen zijn van ervoor.
Ik heb er niet aan gedacht van dat nog eens te controleren. Goed dat je me erop wijst!

2022-04-07 06:40 UTC, leymanan commented on R/read_forresdat.R
> +#' add columns plottype, forest_reserve, survey_dendro/deadw/reg/veg (T or F) and data_processed (T or F)?  Default is TRUE.  (This is only
```suggestion
#' add columns plottype, forest_reserve, survey_dendro/deadw/reg/veg (TRUE or FALSE) and data_processed (TRUE or FALSE)?  Default is TRUE.  (This is only
```

2022-04-07 08:44 UTC, leymanan commented on R/compose_stem_data.R
> +    )
OK! 
Info toegevoegd aan documentatie en ook (soort?) test.

2022-07-01 11:39 UTC, leymanan commented on R/load_data_vegetation.R
> +              tc.Value2 AS mean_cover
ik heb mean_cover verwijderd

2022-07-01 11:49 UTC, leymanan commented
Els, ik denk dat ik al je opmerkingen behandeld heb (reeds in april), en issues als resolved aangeduid.
Maar toch blijft er nog staan "1 change requested" (in rood).
Ligt de bal dan niet terug in jouw kamp?
Ik krijg geen foutmeldingen.

2022-07-05 09:57 UTC, leymanan commented
@ElsLommelen : heel raar, ik dacht dat ik vorige week hier nog een extra comment toegevoegd had, maar ik zie die nu niet meer staan?
Nl. dat ik op dit moment nog problemen heb om te pushen (iets met proxy server ...).
Ik zal een seintje geven wanneer dat opgelost is.
Want ik had nog een foutje gezien (en aangepast) bij berekening van `approx_nr_reg `.
Maar ik kan dat nog niet pushen.

Daarnaast bedacht ik ook dat het beter was om `nr_regeneration_ha `te verwijderen, want dat is - bij exacte aantallen - zelfde als `approx_nr_reg  `en `mean_nr_reg`.
Bovendien geeft dat een misleidende waarde wanneer je op plotniveau totalen berekent, want dan worden enkel die exacte aantallen meegenomen.

2022-07-05 11:01 UTC, ElsLommelen commented
> Daarnaast bedacht ik ook dat het beter was om `nr_regeneration_ha `te verwijderen, want dat is - bij exacte aantallen - zelfde als `approx_nr_reg `en `mean_nr_reg`.

Bekijk sowieso eerst nog eens wat het laatste is wat we hierover afgesproken hebben, want door die benamingen en logica weer eens aan te passen, gaan we weer overal nieuwe problemen creëren, vrees ik.  [Hieruit](https://github.com/inbo/forrescalc/issues/92) blijkt alvast dat we recent nog afgesproken hebben om die te behouden (en dat ze niet overal dezelfde waarde hebben), dus misschien ga je best eerst eens grondig nagaan of dit verwijderen wel kan en of die nergens gebruikt wordt in andere functies?

In verband met het foutje: als het een klein foutje is en je goed oplet om geen typfouten te maken, kan je het altijd op github zelf toevoegen.  Maar je mag uiteraard ook wachten tot het in orde is.  (Je comment van enkele dagen geleden zie ik hier wel, mss je pagina eens refreshen?)

2022-11-28 17:11 UTC, ElsLommelen reviewed
Ik heb de aanpassingen t.o.v. vorige versies doorgenomen, en op basis daarvan heb ik alvast de volgende opmerkingen genoteerd (vooral details, geen fundamentele opmerkingen).
Ik zal morgen ook nog even de scripts zelf testen (a.d.h.v. voorbeelden en main), om zeker te zijn dat aanpassingen in de naamgeving geen problemen veroorzaken.

2022-11-28 17:11 UTC, ElsLommelen commented on R/sum_intervals.R
> +
Weet jij nog voor welk specifiek geval dit toegevoegd is?  Misschien zouden we dit best even vermelden.  (Ik heb even gezocht, maar ik kan niet direct een situatie bedenken waarin lci en sum 0 zijn, en uci NA.)

2022-11-28 17:12 UTC, ElsLommelen commented on R/compose_stem_data.R
> +    )
Ok, je hebt dat zeer goed opgelost!  Al heb ik nog enkele kleine opmerkingen toegevoegd, eigenlijk details om het naar de gebruiker toe nog allemaal iets duidelijker te maken.
Die 'test' zijn de voorbeelden die de gebruikers in de help-functie te zien krijgen (en idealiter meteen kunnen testen, maar hier maakt dat path het wat lastiger)

2022-11-29 08:41 UTC, leymanan commented on R/calculate_vegetation_core_area_species.R
>        n_subplots = n_distinct(.data$subplot_id)
idem dito in `calc_veg_core_area_height_species`

2022-11-29 08:49 UTC, leymanan commented on R/load_data_shoots.R
> +                          ) %>%
nee, die zijn toen niet opgemeten. Bedankt!

2022-11-29 09:04 UTC, leymanan commented on R/load_data_vegetation.R
> +              tc.Value2 AS mid_cover
ja, dat mag, maar eigenlijk wordt met dat veld niks meer gedaan. 
Misschien beter terug verwijderen, komt toch +/- op zelfde neer als min+max/2.
Sorry!

Op einde van functie worden de "mid_covers" (`moss_cover_mid`, ...) vervangen  door min+max/2.

2022-11-29 09:08 UTC, leymanan commented on R/load_data_vegetation.R
> +              tc.Value2 AS mid_cover
ik wou dat zelf verwijderen hier (bij "review changes" van PR), maar ik kan maar één lijn selecteren om suggestie voor te stellen. 
Ik laat het dus aan u, sorry!

2022-11-29 10:43 UTC, leymanan commented on R/sum_intervals.R
> +
Bij `regeneration_by_plot`: overal waar een 0 staat bij mean_number_established/seedlings, staat er een 0 bij lci, en een NA bij uci ....

Daarnaast ook bij `regeneration_by_core_area_(height_)species`, bij `plot_id `11000, 31000, 51000, 71000,  141100, 171200
Maar als ik die bekijk, zijn dat wel enkel records waar geen species vermeld staat (species = NA), eigenlijk zouden die niet in die output moeten zitten ....

Hetzelfde zie ik bij `regeneration_by_plot_height`: als `heightclass `= NA, dan 0 voor mean en lci, maar NA voor uci.
Maar ook hier zijn dat eigenlijk onnodige records (geen heightclass).
Idem dito `regeneration_by_plot_height_species`

2022-11-29 11:56 UTC, leymanan commented on R/calculate_vegetation_plot.R
>  calculate_vegetation_plot <- function(data_vegetation, data_herblayer) {
in scriptregel hierna wordt vertrokken van herblayer, maar dat zou van data_vegetation moeten zijn, anders mis je de plots zonder soorten (momenteel weliswaar maar één plot: plot_id 1176, period 1).

2022-11-29 11:57 UTC, leymanan commented on R/calculate_vegetation_plot.R
>      left_join(
ev. full_join ipv left_join? (zie ook hoger, vorige comment)

2022-11-29 14:10 UTC, ElsLommelen commented on R/load_data_vegetation.R
> +              tc.Value2 AS mid_cover
Tip, dat gaat wel: even vertikaal slepen over de `+`-jes van de opeenvolgende rijen over het bereik waarvoor je suggesties wil voorstellen.  Laat ik je de kans om het meteen te testen?  ;-)

2022-11-30 07:06 UTC, leymanan commented on R/load_data_vegetation.R
> +              tc.Value2 AS mid_cover
Goede tip, bedankt! Ik probeer!
Heb je ook een tip voor wanneer de code niet gewijzigd iss en dan grijs staat (enkel zichtbaar na uitklappen van code)?
Want daar verschijnen geen plusjes ;-)

2022-11-30 07:08 UTC, leymanan commented on R/load_data_vegetation.R
> +              tc.Value2 AS mid_cover
```suggestion
      "SELECT tc.ID AS id,
              tc.Value1 AS cover_interval
```

2022-11-30 08:37 UTC, ElsLommelen commented on R/load_data_vegetation.R
> +              tc.Value2 AS mid_cover
Bij mijn weten kan dat niet bij het reviewen, idee is namelijk om de nieuwe code te reviewen.

Hoe je wel nieuwe aanpassingen kan doen op GitHub zelf, is naar de branch navigeren (bv. heel bovenaan op 'reg_AL' klikken, of naar tab code gaan en daar bij branch 'reg_AL' selecteren), daar naar de file in kwestie navigeren, rechtsboven het document op edit klikken (potloodje, vermoed ik), de aanpassing maken, en dan onderaan kiezen om een nieuwe branch te maken en een PR naar 'reg_AL'.  (Dit pas ik weleens toe als ik in een package van een collega een typo zie, en ik het wat veel werk vind om dat package binnen te halen om die typo te melden, en ik ook een issue maken omslachtig vind voor zo'n kleinigheidje.  Voor code-aanpassingen is het uiteraard veiliger om dit lokaal te doen, zodat je het ook kan testen (al ga ik het nu sowieso nog wel lokaal testen).)

2023-10-27 14:50 UTC, ElsLommelen commented
@leymanan Ik ben - denk ik - ooit eens gestart met een branch bug-fixes vanuit deze branch met het idee om enkele fixes voor te stellen en die dan in deze branch te mergen, maar blijkbaar ben ik er nooit toe gekomen om deze af te werken en een PR te maken.  (In elk geval is er een branch bug-fixes die start vanaf de laatste commit van deze branch.)  Zou het een idee zijn om gewoon met die bug-fixes verder te gaan, daar alle issues in op te lossen, en dan die uiteindelijk rechtstreeks naar de master te mergen na review door u?
Zijn er hierboven nog zaken uit de commentaren die ingewerkt moeten worden?  Want dan is dat misschien niet de beste optie.

2023-10-30 09:38 UTC, leymanan commented
> @leymanan Ik ben - denk ik - ooit eens gestart met een branch bug-fixes vanuit deze branch met het idee om enkele fixes voor te stellen en die dan in deze branch te mergen, maar blijkbaar ben ik er nooit toe gekomen om deze af te werken en een PR te maken. (In elk geval is er een branch bug-fixes die start vanaf de laatste commit van deze branch.) Zou het een idee zijn om gewoon met die bug-fixes verder te gaan, daar alle issues in op te lossen, en dan die uiteindelijk rechtstreeks naar de master te mergen na review door u? Zijn er hierboven nog zaken uit de commentaren die ingewerkt moeten worden? Want dan is dat misschien niet de beste optie.

Had eerst niet door wat je bedoelde met "Zijn er hierboven nog zaken uit de commentaren die ingewerkt moeten worden? Want dan is dat misschien niet de beste optie."? 
Maar als ik het goed begrijp is bug_fixes vertrokken van "mijn" reg_AL, vóór alle bovenstaande comments? 
Maar die moeten inderdaad meegenomen worden.
Kan er niet een merge gebeuren van bug_fixes en reg_AL (met oplossingen zoals hierboven)?
En dan verder gaan met bug-fixes?
Ik heb bovenstaande comments nog niet allemaal opnieuw doorgenomen, maar 't zijn er veel ...

Of wat bedoel je met "moeten ingewerkt worden"? Ik heb die allemaal ooit beantwoord.

2023-10-30 09:48 UTC, ElsLommelen commented on R/sum_intervals.R
> +
Blijkbaar is het probleem hier dat de `variance` oneindig wordt als `var_min` en `var_max` 0 zijn en dit enkel ingeval van een log-transformatie.  In commit b199661e5e6cf09a05f40e7ff144a9e901fbc156 in branch bug-fixes heb ik dit vervangen door een meer specifiek commando dat `uci` moet gelijkgesteld worden aan het gemiddelde (variabele `sum`) als de `variance` oneindig is én het over log-transformatie gaat.  Dit lijkt me iets veiliger dan zomaar generiek een NA te vervangen door 0 in alle mogelijke gevallen.  Ik heb je specifiek geval niet onderzocht, maar ik veronderstel dat dit hiermee ook opgelost is?

2023-10-30 09:59 UTC, leymanan commented on R/sum_intervals.R
> +
ok!

2023-10-30 10:09 UTC, ElsLommelen commented on R/compose_stem_data.R
> +#' extra_variables = TRUE.
opgelost in commit [22c606a](https://github.com/inbo/forrescalc/pull/100/commits/22c606a31b28b87ae81a798467566187caa3b3bb) (hieronder, en die zit ook in branch bug-fixes)

2023-10-30 10:56 UTC, ElsLommelen commented
> Had eerst niet door wat je bedoelde met "Zijn er hierboven nog zaken uit de commentaren die ingewerkt moeten worden? Want dan is dat misschien niet de beste optie."?
> Maar als ik het goed begrijp is bug_fixes vertrokken van "mijn" reg_AL, vóór alle bovenstaande comments?
> Maar die moeten inderdaad meegenomen worden.

bug-fixes is vertrokken van reg_AL na de commits van de comments, dus dat is niet het probleem.  Probleem is vooral: zijn alle andere commentaren ingewerkt?  Je hebt inderdaad overal wel op gereageerd, maar het is niet altijd duidelijk of er ook actie ondernomen is.  Enfin, ik ben intussen bezig om dat stap voor stap te checken, en eventuele nodige aanpassingen rechtstreeks in bug-fixes te doen.  En waar onduidelijkheid is over de status, voeg ik ook een nota toe, evt. gewoon om aan te geven dat het opgelost is.  En ik zal ze ook resolven.

2023-10-30 11:30 UTC, ElsLommelen commented on R/calculate_vegetation_core_area_species.R
>        n_subplots = n_distinct(.data$subplot_id)
Euh, dit is een vreemde situatie die je best nog even bekijkt, @leymanan :

Blijkbaar heb je in deze functie het argument data_vegetation toegevoegd zonder het te gebruiken (zie [hier](https://github.com/inbo/forrescalc/blame/bug-fixes/R/calculate_vegetation_core_area_species.R#L41)), en ook zonder de documentatie hieraan aan te passen.  Maar dit argument lijkt me niet nodig te zijn?  Mag dit terug weg?  (Zie eerst hieronder.)

> @ElsLommelen : hier nog een foutje ontdekt: `n_subplots` zou moeten bepaald worden obv `data_vegetation`, want in `data_herblayer `zitten enkel de subplots waar minimum één soort waargenomen werd. In `data_vegetation ` zitten alle subplots.
> (Bij regeneration wordt `n_subplots `bepaald obv de regeneration layer, wat wel correct is)

De `subplot_id` die opgehaald wordt in `load_data_herblayer()`, is afkomstig uit tabel Vegetation uit de databank (zie [hier](https://github.com/inbo/forrescalc/blob/b199661e5e6cf09a05f40e7ff144a9e901fbc156/R/load_data_herblayer.R#L49)), dus ik ga ervan uit dat dit wel in orde is?

> idem dito in `calc_veg_core_area_height_species`

Functie `calc_veg_core_area_height_species()` zie ik nergens staan, kan het zijn dat die nooit toegevoegd is?  Moet die toegevoegd worden?

2023-10-30 11:40 UTC, ElsLommelen commented on R/calculate_vegetation_plot.R
>  calculate_vegetation_plot <- function(data_vegetation, data_herblayer) {
Ik vermoed dat dit beter in de query in `load_data_herblayer()` opgelost wordt?  Hier worden sowieso de id's van tabel vegetatie mee binnengehaald, en ook de info over het jaar van het onderzoek, dus ik veronderstel dat ik best daar de query aanpas zodat alle plots meegenomen worden, ook die zonder soorten en records in herblayer?  Of zie ik iets over het hoofd waardoor die optie toch niet wenselijk is?

2023-10-30 11:48 UTC, leymanan commented on R/calculate_vegetation_core_area_species.R
>        n_subplots = n_distinct(.data$subplot_id)
in [deze commit](https://github.com/inbo/forrescalc/commit/f579319ca3004dfc74d8ab4799d2d5d21d750e6e#diff-ee5b57ecbe6ce84c508744fae9c60d15cfd4f78aa510dfd614d3e804be27c1e5) zie ik anders wel gebruik van data_vegetation?

ik denk nog steeds dat dit nodig is.

> De `subplot_id` die opgehaald wordt in `load_data_herblayer()`, is afkomstig uit tabel Vegetation uit de databank (zie [hier](https://github.com/inbo/forrescalc/blob/b199661e5e6cf09a05f40e7ff144a9e901fbc156/R/load_data_herblayer.R#L49)), dus ik ga ervan uit dat dit wel in orde is?

daar wordt een inner-join gemaakt tss Herblayer en Vegetation: dus als er een bepaald record niet aanwezig is in Herblayer (wegens geen enkele soort aanwezig), dan wordt die `subplot_id `niet opgepikt ...


> Functie `calc_veg_core_area_height_species()` zie ik nergens staan, kan het zijn dat die nooit toegevoegd is? Moet die toegevoegd worden?

Height wordt enkel bij regeneration gebruikt (calculate_regeneration_core_area_height_species.R bestaat)
`calc_veg_core_area_height_species()` niet nodig ;-)

2023-10-30 12:03 UTC, leymanan commented on R/calculate_vegetation_plot.R
>  calculate_vegetation_plot <- function(data_vegetation, data_herblayer) {
nee, is ok, maar kan je hier ook zorgen dat enkel deze waar een opname gebeurd is, meegenomen worden (survey_veg = TRUE), want voor start veldseizoen worden in Fieldmap automatisch alle vegetatie records aangemaakt (om gis-component te hebben)

2023-10-30 13:04 UTC, ElsLommelen commented on R/calculate_vegetation_core_area_species.R
>        n_subplots = n_distinct(.data$subplot_id)
> in [deze commit](https://github.com/inbo/forrescalc/commit/f579319ca3004dfc74d8ab4799d2d5d21d750e6e#diff-ee5b57ecbe6ce84c508744fae9c60d15cfd4f78aa510dfd614d3e804be27c1e5) zie ik anders wel gebruik van data_vegetation?

Dat is een commit van meer dan 2 jaar geleden, en intussen is de code blijkbaar veranderd en is het inladen van `data_vegetation` overbodig geworden.  Ik heb even gezocht waar die `data_vegetation` gewist is, maar ik kan het niet terugvinden.  Ik vermoed dat we dat we op een bepaald moment beslist hebben om die `subplot_id` in `load_data_herblayer()` op te halen om gebruikers niet te verplichten om voor `calculate_vegetation_core_area_species()` behalve `load_data_herblayer()` ook `load_data_vegetation()` te moeten opladen enkel om dat ene item `subplot_id` op te laden.  Maar blijkbaar zijn we daarbij vergeten om de join in `load_data_herblayer()` aan te passen.

> daar wordt een inner-join gemaakt tss Herblayer en Vegetation: dus als er een bepaald record niet aanwezig is in Herblayer (wegens geen enkele soort aanwezig), dan wordt die `subplot_id `niet opgepikt ...

Zal ik er daar een left join van maken?  Dus Plots inner join Vegetation LEFT JOIN Herblayer.  (Vermits het access is, zal ik ook nog met de haakjes moeten spelen enz., maar ik neem aan dat je wel weet wat ik bedoel.)  Dit lijkt me een veel minder ingrijpende aanpassing als het functioneel toevoegen van `data_vegetation` in `calculate_vegetation_core_area_species()`.

2023-10-30 14:29 UTC, ElsLommelen commented on R/calculate_vegetation_core_area_species.R
>        n_subplots = n_distinct(.data$subplot_id)
Ok, opgelost in commit cf9068492e7ef9755addc9686ee1e3b8c35b540e (left join in Access ziet er wel iets complexer uit dan gewone SQL omdat hier de mix van inner join en left join in Access niet kan zonder met een subquery te werken).
Die selectie survey_veg = TRUE gebeurt blijkbaar [hier](https://github.com/inbo/forrescalc/blob/b199661e5e6cf09a05f40e7ff144a9e901fbc156/R/load_data_herblayer.R#L38) in `load_data_herblayer()`, dus dat zou ook in orde moeten zijn.

2023-10-30 14:38 UTC, ElsLommelen commented on R/calculate_vegetation_plot.R
>  calculate_vegetation_plot <- function(data_vegetation, data_herblayer) {
Ik heb de functie getest en de hierboven vermelde plot (plot_id 1176) wordt inderdaad binnengehaald en heeft voor periode 1 maar 1 record bij NA voor de soorten.  Als ik de hele dataset bekijk (CP en CA over alle periodes heen), zijn er 122 records met NA, vnl. afkomstig van 3 CA-plots uit de eerste periode: Kersselaerspleyn, Hannecart en Rodebos KV2.  Maar het kan dat ik met een hopeloos verouderde versie van de databank aan 't werken ben.
Misschien dat jij bij gelegenheid best ook nog even test of het in orde is? (Moet niet direct nu, maak gerust een lijstje om eens te doen als het uitkomt, ik ga hier toch nog wel een tijdje mee bezig zijn.  ;-) )

2023-10-30 14:54 UTC, ElsLommelen commented on R/calculate_vegetation_plot.R
>      left_join(
Wat doe ik in dat geval met `number_of_species` en `cumm_herb_coverage_class_average_perc`?  Als ze geen overeenkomstige waarden hebben in `data_vegetation`, gaan ze NA zijn.  Is dat ok, of moet dat dan 0 worden?
Sowieso, gezien het feit dat `load_data_herblayer()` ook alle plots meeneemt, zou dit niet kunnen voorkomen, tenzij de gebruiker in `load_data_vegetation()` niet dezelfde dataset opgevraagd heeft (bv. ander plottype of forest_reserve).  Dus ik zou ook een anti_join kunnen doen als foutencheck, of is dat niet nodig?

Enfin, laat maar weten of er nog iets moet gebeuren met je opmerking, daarna kunnen we dit hoofdstuk (opmerkingen reg_AL) stilaan afsluiten.

2023-10-30 14:55 UTC, ElsLommelen commented on R/load_data_vegetation.R
> +              tc.Value2 AS mid_cover
resolve ik deze, of wil je bovenstaande suggestie nog ergens noteren voor moest je ze ooit nodig hebben?  ;-)

2024-05-08 13:48 UTC, ElsLommelen commented
@leymanan Zou jij nog eens even willen kijken of deze PR dicht mag?  Situatie is dat testdatabase (of ene voorganger) vertrokken is van deze branch, dus alle commits zitten in de huidige versie en de PR zelf moet dus niet gemerged worden.  Maar hierin staan (zeker op het einde na de commits) nog een aantal opmerkingen waarvan voor mij niet duidelijk is of hier wel gevolg aan gegeven is.  Soms weet ik niet goed wat je bedoelt of waarom je iets wil, dus voor mij is het heel moeilijk inschatten of er nog iets relevants tussen zit.  Zo stel je bv. in je laatste opmerking op het script voor om een left_join() te vervangen door een full_join(), maar ik snap niet waarom, en op mijn vragen hierover is nooit een reactie gekomen.  En zo zijn er nog enkele opmerkingen hierboven.  Kan jij eens nakijken of er nog iets tussen zit waar best toch nog gevolg aan gegeven kan worden?  (Je laatste review is goed hoor.)  Als het voor u allemaal in orde is, mag deze PR voor mij gesloten.

2024-05-14 11:57 UTC, leymanan commented on R/calculate_vegetation_plot.R
>      left_join(
reden voor full_join is achterhaald, opgevangen in `load_data_herblayer() `
Nu bevat data_herblayer immers ook al de "lege" plots, zonder kruidlaag (species = NA)

2024-05-14 11:58 UTC, closed without merging